wallets:
  - "9WzDXwBbmkg8ZTbNMqUxvQRAyrZzDsGYdLVL9zYtAWWM"
  - "HN7cABqLq46Es1jh92dQQisAq662SmxELLLsHHe4YWrH"
  - "7npDRsTxvsG5QFmEZr8znKYWPHuai3d5FUu1RrCwv1Wv"
  - "6x1P2mBDDhYn879m7yAjuw4ijhVeD5Ms46Wrvnq6pdtk"
  - "2k3uSEFYyWAczsYyjMqPtVugqcrDjVeLTVetDUaBo8y9"
  - "HbjRwJqFQJxEEhczcPznd8BJci3wj9fRzAPsP8bSuvCN"
  - "7i3waUWg8aXnSe6E4Hi7EqbuAXSm86tw4d21hPJNsoZv"